### ISSUE TITLE
[Question] Framework produces both static and dynamic output

### ISSUE THREAD

**Issue by kientux** [tmspzz/Rome#230]
My app has [`SocketRocket`](https://github.com/kientux/SocketRocket) as dependency. It produces both static and dynamic output. Rome will upload only static OR dynamic framework so everytime I use `rome download`, carthage will report that `SocketRocket` cache is not valid, and it will rebuild.

Is there any option that specify a framework is both dynamic and static?

**Comment by tmspzz** [comment]
I am not sure. You can maybe try:

```
repositoryMap:
- SocketRocket: 
  - name: SocketRocket
    type: static
  - name: SocketRocket
    type: dynamic
```

If it doesn't work...It's simply something I didn't think of 😓 

I can think of maybe another hack where you can have 2 `Romefile`s. The second one would have just the static or dynamic version in the` repositoryMap`.
