### ISSUE TITLE
Static folder isn't uploaded to remote server on Xcode 12

### ISSUE THREAD

**Issue by feng-caffeine** [tmspzz/Rome#233]
## Bug Report 

Since Xcode 12, Carthage created a new folder called `Static` under `Carthage/Build/` for some libraries. Actually, I don't know what `Static` is for. An example of framework in `Static` folder structure looks like,

```
- Static
  |- FBSDKShareKit.framework
      |- Headers
      |- FBSDKShareKit
      |- Modules
          |- FBSDKShareKit.swiftmodule
          |- module.modulemap
      |- Info.plist
  |
```

Since this folder isn't copied into S3, the cache is invalidated and the error show `Invalid cache found for facebook-ios-sdk, rebuilding all downstream dependencies when running `carthage bootstrap --platform iOS --cache-builds --no-use-binaries`. The build speed on CI is significant reduced.

**Steps which explain the enhancement or reproduce the bug**

1. Romefile configuration sample
```
repositoryMap:
- facebook-ios-sdk:
  - name: FBSDKCoreKit
  - name: FBSDKGamingServicesKit
  - name: FBSDKLoginKit
  - name: FBSDKShareKit
```

2. Download Command
`rome download --platform iOS`

3. Upload Command
`rome upload --platform iOS`

**Current behavior**

Some libraries, like `facebook-ios-sdk`, have to rebuild every time due to miss `static`.

**Suggested behavior**

Those libraries should be cached properly.

**Rome version:** 

0.23

**OS and version:** 

Xcode 12, Carthage 0.36
