### ISSUE TITLE
Issues running Rome with --no-skip-current

### ISSUE THREAD

**Issue by mpdifran** [tmspzz/Rome#237]
## Bug Report 

I'm not sure if my project is set up correctly or not, but I can't seem to get Rome to work with the `--no-skip-current` option.

**Steps which explain the enhancement or reproduce the bug**

Here's my setup:

GitHub repo: 
```
Faire/ios-protobuf
// Produces FaireProtobuf.framework
```

Romefile:
```
cache:
  local: ~/Library/Caches/Rome

repositoryMap:
- swift-protobuf:
  - name: SwiftProtobuf

# Not sure if this is set up properly
currentMap:
- ios-protobuf:
  - name: FaireProtobuf
```

Rome command:
```
rome upload --no-skip-current
```

**Current behavior**

Rome does not upload for the FaireProtobuf framework.

**Suggested behavior**

I'd like Rome to cache all Carthage dependencies, including the FaireProtobuf framework when the `--no-skip-current` is specified.

**Why would the enhancement be useful to most users**

This is useful for framework projects that need to be pre-cached.

**Rome version:** 

```
0.23.3.64 - Romam uno die non fuisse conditam.
```

**OS and version:** 

macOS Big Sur 11.1 (20C69)

**Comment by tmspzz** [comment]
This is equivalent to Carthage's --no-skip-current. Try removing the repositoryMap.

You can check in the integration tests of the project how this is set up for Alamofire I think

**Comment by mpdifran** [comment]
Ah thanks for the tip. Looks like the [integration tests](https://github.com/tmspzz/Rome/blob/4c68baf1c235fea20840622bfa24c5763bcecd90/integration-tests/current-framework-yml.bats) are using this Romefile:
```
cache:
  local: rome-local-cache
  s3Bucket: rome
ignoreMap:
  - Alamofire:
    - name: Alamofire
      platforms: [Mac]
currentMap:
  - Alamofire:
    - name: Alamofire
```
with the following Rome command:
```
rome upload --concurrently --cache-prefix travis --no-skip-current
```

I've revised my Romefile to this:
```
cache:
  local: ~/Library/Caches/Rome

currentMap:
- ios-protobuf:
  - name: FaireProtobuf
```

Here's the commands I'm running:
```
rome upload --no-skip-current // Uploads my framework's dependencies, but not my framework

rome upload --no-skip-current ios-protobuf -v // Uploads nothing, outputs nothing

rome upload --no-skip-current FaireProtobuf -v // Uploads nothing, outputs nothing
```

One thing to note: My project has a regular `.xcodeproj` file, as well as a `Package.swift`. Not sure if that has any effect.
